# Install script for directory: /home/twal/Documents/dev/Jeux/unv_bullet/Demos

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "Release")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/HelloWorld/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/OpenGL/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/AllBulletDemos/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/CcdPhysicsDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/BulletXmlImportDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConstraintDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/SliderConstraintDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/GenericJointDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/Raytracer/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/RagdollDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ForkLiftDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/BasicDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/RollingFrictionDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/RaytestDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/VoronoiFractureDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/GyroscopicDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/FractureDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/Box2dDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/BspDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/MovingConcaveDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/VehicleDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/CharacterDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/SoftDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/SimplexDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/DynamicControlDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConvexHullDistance/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/DoublePrecisionDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConcaveDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/CollisionDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ContinuousConvexCollision/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/GjkConvexCastDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/MultiMaterialDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/SerializeDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/InternalEdgeDemo/cmake_install.cmake")
  INCLUDE("/home/twal/Documents/dev/Jeux/unv_bullet/Demos/Benchmarks/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

